import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';

import '@/app/globals.css';
import { LocalizationContextProvider } from '@/components/localization-context';
import { UpdateDialogProvider } from '@/components/UpdateDialogContext';
import { DeepLinkProvider } from '@/components/deep-link-provider';
import { PatreonProvider } from '@/contexts/patreon-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const normalizeStoredThemeScript = `(()=>{try{const themeKey='theme';const storedTheme=window.localStorage.getItem(themeKey);if(!storedTheme){return}const parsedTheme=JSON.parse(storedTheme);if(typeof parsedTheme!=='string'||!['light','dark','system'].includes(parsedTheme)){return}window.localStorage.setItem(themeKey,parsedTheme);const root=document.documentElement;root.classList.remove(storedTheme);const resolvedTheme=parsedTheme==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':parsedTheme==='system'?'light':parsedTheme;root.classList.remove('light','dark');root.classList.add(resolvedTheme);root.style.colorScheme=resolvedTheme}catch{}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script id="normalize-stored-theme" strategy="beforeInteractive">
          {normalizeStoredThemeScript}
        </Script>
        <DeepLinkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocalizationContextProvider>
              <UpdateDialogProvider>
                <PatreonProvider>
                  <main>{children}</main>
                </PatreonProvider>
              </UpdateDialogProvider>
            </LocalizationContextProvider>
          </ThemeProvider>
          <Toaster richColors />
        </DeepLinkProvider>
      </body>
    </html>
  );
}
