import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';

import '@/app/globals.css';
import { LocalizationContextProvider } from '@/components/localization-context';
import { UpdateDialogProvider } from '@/components/UpdateDialogContext';
import { DeepLinkProvider } from '@/components/deep-link-provider';
import { PatreonProvider } from '@/contexts/patreon-context';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// This must run before next-themes initializes to avoid first-paint theme mismatch
// while migrating legacy quoted values (e.g. `"system"`).
const normalizeStoredThemeScript = `
  (() => {
    const themeKey = 'theme';
    const storedTheme = window.localStorage.getItem(themeKey);
    const validThemes = ['light', 'dark', 'system'];

    if (!storedTheme || validThemes.includes(storedTheme)) {
      return;
    }

    const legacyThemeMatch = storedTheme.match(/^"(light|dark|system)"$/);

    if (!legacyThemeMatch) {
      return;
    }

    const normalizedTheme = legacyThemeMatch[1];
    const root = document.documentElement;
    const resolvedTheme =
      normalizedTheme === 'system'
        ? window.matchMedia('(prefers-color-scheme: dark)').matches
          ? 'dark'
          : 'light'
        : normalizedTheme;

    window.localStorage.setItem(themeKey, normalizedTheme);

    root.classList.remove(storedTheme);
    root.classList.remove('light', 'dark');
    root.classList.add(resolvedTheme);
    root.style.colorScheme = resolvedTheme;
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script id="normalize-stored-theme" strategy="beforeInteractive">
          {normalizeStoredThemeScript}
        </Script>
        <DeepLinkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocalizationContextProvider>
              <UpdateDialogProvider>
                <PatreonProvider>
                  <main>{children}</main>
                </PatreonProvider>
              </UpdateDialogProvider>
            </LocalizationContextProvider>
          </ThemeProvider>
          <Toaster richColors />
        </DeepLinkProvider>
      </body>
    </html>
  );
}
